version: '3.8'

services:

  app-frontend:
    image: patientor-client-production
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # env_file:
    #   - ./client/.env
    volumes:
      - ./client/:/usr/src/app
      # - /usr/src/app/node_modules
    container_name: patientor-client-production
  
  app-backend:
    image: patientor-server-production
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    env_file:
      - ./server/.env
    # environment:
      # - REACT_APP_BACKEND_URL=http://localhost:8080/api/
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    container_name: patientor-server-production