version: '3.8'

services:

  app-frontend:
    image: patientor-client-dev
    build:
      context: ./client
      dockerfile: ./dev.Dockerfile
    ports:
      - 3000:3000
    # env_file:
    #   - ./client/.env  
    volumes:
      - ./client/:/usr/src/app
      # - /usr/src/app/node_modules
    container_name: patientor-client-dev
  
  app-backend:
    image: patientor-server-dev
    build:
      context: ./server
      dockerfile: ./dev.Dockerfile
    ports:
      - 3001:3001
    secrets:
      - my_secret
    env_file: 
      - ./server/.env
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    container_name: patientor-server-dev